<?php
namespace In2code\Femanager\Domain\Model;

/**
 * Interface UserInterface
 * @package In2code\Femanager\Domain\Model
 */
interface UserInterface
{
    public function setUsername($username);
    public function getUsername();
    public function setPassword($password);
    public function getPassword();
    public function setUsergroup(\TYPO3\CMS\Extbase\Persistence\ObjectStorage $usergroup);
    public function addUsergroup(\TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup $usergroup);
    public function removeUsergroup(\TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup $usergroup);
    public function getUsergroup();
    public function setName($name);
    public function getName();
    public function setFirstName($firstName);
    public function getFirstName();
    public function setMiddleName($middleName);
    public function getMiddleName();
    public function setLastName($lastName);
    public function getLastName();
    public function setAddress($address);
    public function getAddress();
    public function setTelephone($telephone);
    public function getTelephone();
    public function setFax($fax);
    public function getFax();
    public function setEmail($email);
    public function getEmail();
    public function setLockToDomain($lockToDomain);
    public function getLockToDomain();
    public function setTitle($title);
    public function getTitle();
    public function setZip($zip);
    public function getZip();
    public function setCity($city);
    public function getCity();
    public function setCountry($country);
    public function getCountry();
    public function setWww($www);
    public function getWww();
    public function setCompany($company);
    public function getCompany();
    public function setImage($image);
    public function getImage();
    public function setLastlogin(\DateTime $lastlogin);
    public function getLastlogin();

    public function setGender($gender);
    public function getGender();
    public function setDateOfBirth($dateOfBirth);
    public function getDateOfBirth();
    public function setTxExtbaseType($txExtbaseType);
    public function getTxExtbaseType();
    public function setTxFemanagerChangerequest($txFemanagerChangerequest);
    public function getTxFemanagerChangerequest();
    public function setCrdate($crdate);
    public function getCrdate();
    public function setTstamp($tstamp);
    public function getTstamp();
    public function setDisable($disable);
    public function getDisable();
    public function setTxFemanagerConfirmedbyadmin($txFemanagerConfirmedbyadmin);
    public function getTxFemanagerConfirmedbyadmin();
    public function setTxFemanagerConfirmedbyuser($txFemanagerConfirmedbyuser);
    public function getTxFemanagerConfirmedbyuser();
    public function setIgnoreDirty($ignoreDirty);
    public function getIgnoreDirty();
    public function setPasswordAutoGenerated($passwordAutoGenerated);
    public function getPasswordAutoGenerated();

    public function isOnline();
    public function _isDirty($propertyName = null);

    public function removeAllUsergroups();
}
